<a href="https://colab.research.google.com/github/yuvarajrajdata/AIDATADRIVEN_Task/blob/main/Task_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/loan_dataset - Copy.csv')
df.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [ ]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
# find duplicates and print
duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [ ]:
# drop duplicates rows
df = df.drop_duplicates()

In [ ]:
# droping NaN values :
df.dropna(subset=df.columns, inplace=True)

In [ ]:
# find columns with dtypes as object
df1 = df.select_dtypes(include=['object'])

In [ ]:
for i in df1.columns:
  print(i,':',df[i].unique())

Loan_ID : ['LP001003' 'LP001005' 'LP001006' 'LP001008' 'LP001011' 'LP001013'
 'LP001014' 'LP001018' 'LP001020' 'LP001024' 'LP001028' 'LP001029'
 'LP001030' 'LP001032' 'LP001036' 'LP001038' 'LP001043' 'LP001046'
 'LP001047' 'LP001066' 'LP001068' 'LP001073' 'LP001086' 'LP001095'
 'LP001097' 'LP001098' 'LP001100' 'LP001112' 'LP001114' 'LP001116'
 'LP001119' 'LP001120' 'LP001131' 'LP001138' 'LP001144' 'LP001146'
 'LP001151' 'LP001155' 'LP001157' 'LP001164' 'LP001179' 'LP001186'
 'LP001194' 'LP001195' 'LP001197' 'LP001198' 'LP001199' 'LP001205'
 'LP001206' 'LP001207' 'LP001222' 'LP001225' 'LP001228' 'LP001233'
 'LP001238' 'LP001241' 'LP001243' 'LP001245' 'LP001248' 'LP001253'
 'LP001255' 'LP001256' 'LP001259' 'LP001263' 'LP001265' 'LP001267'
 'LP001275' 'LP001279' 'LP001282' 'LP001289' 'LP001310' 'LP001316'
 'LP001318' 'LP001319' 'LP001322' 'LP001325' 'LP001327' 'LP001333'
 'LP001334' 'LP001343' 'LP001345' 'LP001349' 'LP001367' 'LP001369'
 'LP001379' 'LP001384' 'LP001385' 'LP001401' 'LP001404' 'LP001421'
 'LP001422' 'LP001430' 'LP001431' 'LP001432' 'LP001439' 'LP001451'
 'LP001473' 'LP001478' 'LP001482' 'LP001487' 'LP001488' 'LP001489'
 'LP001491' 'LP001492' 'LP001493' 'LP001497' 'LP001498' 'LP001504'
 'LP001507' 'LP001508' 'LP001514' 'LP001516' 'LP001518' 'LP001519'
 'LP001520' 'LP001528' 'LP001529' 'LP001531' 'LP001532' 'LP001535'
 'LP001536' 'LP001543' 'LP001552' 'LP001560' 'LP001562' 'LP001565'
 'LP001570' 'LP001572' 'LP001577' 'LP001578' 'LP001579' 'LP001580'
 'LP001586' 'LP001594' 'LP001603' 'LP001606' 'LP001608' 'LP001610'
 'LP001616' 'LP001630' 'LP001633' 'LP001636' 'LP001637' 'LP001639'
 'LP001640' 'LP001641' 'LP001647' 'LP001653' 'LP001656' 'LP001657'
 'LP001658' 'LP001664' 'LP001665' 'LP001666' 'LP001673' 'LP001674'
 'LP001677' 'LP001688' 'LP001691' 'LP001692' 'LP001693' 'LP001698'
 'LP001699' 'LP001702' 'LP001708' 'LP001711' 'LP001713' 'LP001715'
 'LP001716' 'LP001720' 'LP001722' 'LP001726' 'LP001736' 'LP001743'
 'LP001744' 'LP001750' 'LP001751' 'LP001758' 'LP001761' 'LP001765'
 'LP001776' 'LP001778' 'LP001784' 'LP001790' 'LP001792' 'LP001798'
 'LP001800' 'LP001806' 'LP001807' 'LP001811' 'LP001813' 'LP001814'
 'LP001819' 'LP001824' 'LP001825' 'LP001835' 'LP001836' 'LP001841'
 'LP001843' 'LP001844' 'LP001846' 'LP001849' 'LP001854' 'LP001859'
 'LP001868' 'LP001870' 'LP001871' 'LP001872' 'LP001875' 'LP001877'
 'LP001882' 'LP001884' 'LP001888' 'LP001891' 'LP001892' 'LP001894'
 'LP001896' 'LP001900' 'LP001903' 'LP001904' 'LP001907' 'LP001910'
 'LP001914' 'LP001915' 'LP001917' 'LP001924' 'LP001925' 'LP001926'
 'LP001931' 'LP001935' 'LP001936' 'LP001938' 'LP001940' 'LP001947'
 'LP001953' 'LP001954' 'LP001955' 'LP001963' 'LP001964' 'LP001974'
 'LP001977' 'LP001978' 'LP001993' 'LP001994' 'LP001996' 'LP002002'
 'LP002004' 'LP002006' 'LP002031' 'LP002035' 'LP002050' 'LP002051'
 'LP002053' 'LP002065' 'LP002067' 'LP002068' 'LP002082' 'LP002086'
 'LP002087' 'LP002097' 'LP002098' 'LP002112' 'LP002114' 'LP002115'
 'LP002116' 'LP002119' 'LP002126' 'LP002129' 'LP002131' 'LP002138'
 'LP002139' 'LP002140' 'LP002141' 'LP002142' 'LP002143' 'LP002149'
 'LP002151' 'LP002158' 'LP002160' 'LP002161' 'LP002170' 'LP002175'
 'LP002180' 'LP002181' 'LP002187' 'LP002190' 'LP002191' 'LP002194'
 'LP002197' 'LP002201' 'LP002205' 'LP002211' 'LP002219' 'LP002224'
 'LP002225' 'LP002229' 'LP002231' 'LP002234' 'LP002236' 'LP002239'
 'LP002244' 'LP002250' 'LP002255' 'LP002262' 'LP002265' 'LP002266'
 'LP002277' 'LP002281' 'LP002284' 'LP002287' 'LP002288' 'LP002296'
 'LP002297' 'LP002300' 'LP002301' 'LP002305' 'LP002308' 'LP002314'
 'LP002315' 'LP002317' 'LP002318' 'LP002328' 'LP002332' 'LP002335'
 'LP002337' 'LP002341' 'LP002342' 'LP002345' 'LP002347' 'LP002348'
 'LP002361' 'LP002364' 'LP002366' 'LP002367' 'LP002368' 'LP002369'
 'LP002370' 'LP002377' 'LP002379' 'LP002387' 'LP002390' 'LP002398'
 'LP002403' 'LP002407' 'LP002408' 'LP002409' 'LP002418' 'LP002422'
 'LP002429' 'LP002434' 'LP002443' 'LP002446' 'LP002448' 'LP002449'
 'LP002453' 'LP002455' 'LP002459' 'LP002467' 'LP002472' 'LP002473'
 'LP002484' 'LP002487' 'LP002493' 'LP002494' 'LP002500' 'LP002505'
 'LP002515' 'LP002517' 'LP002519' 'LP002524' 'LP002527' 'LP002529'
 'LP002531' 'LP002534' 'LP002536' 'LP002537' 'LP002541' 'LP002543'
 'LP002544' 'LP002545' 'LP002547' 'LP002555' 'LP002556' 'LP002571'
 'LP002582' 'LP002585' 'LP002586' 'LP002587' 'LP002600' 'LP002602'
 'LP002603' 'LP002606' 'LP002615' 'LP002619' 'LP002622' 'LP002626'
 'LP002634' 'LP002637' 'LP002640' 'LP002643' 'LP002648' 'LP002652'
 'LP002659' 'LP002670' 'LP002683' 'LP002684' 'LP002689' 'LP002690'
 'LP002692' 'LP002693' 'LP002699' 'LP002705' 'LP002706' 'LP002714'
 'LP002716' 'LP002720' 'LP002723' 'LP002731' 'LP002734' 'LP002738'
 'LP002739' 'LP002740' 'LP002741' 'LP002743' 'LP002755' 'LP002767'
 'LP002768' 'LP002772' 'LP002776' 'LP002777' 'LP002785' 'LP002788'
 'LP002789' 'LP002792' 'LP002795' 'LP002798' 'LP002804' 'LP002807'
 'LP002813' 'LP002820' 'LP002821' 'LP002832' 'LP002836' 'LP002837'
 'LP002840' 'LP002841' 'LP002842' 'LP002855' 'LP002862' 'LP002863'
 'LP002868' 'LP002874' 'LP002877' 'LP002892' 'LP002893' 'LP002894'
 'LP002911' 'LP002912' 'LP002916' 'LP002917' 'LP002926' 'LP002928'
 'LP002931' 'LP002936' 'LP002938' 'LP002940' 'LP002941' 'LP002945'
 'LP002948' 'LP002953' 'LP002958' 'LP002959' 'LP002961' 'LP002964'
 'LP002974' 'LP002978' 'LP002979' 'LP002983' 'LP002984' 'LP002990']
Gender : ['Male' 'male' 'M' 'Female' 'F']
Married : ['Yes' 'No']
Dependents : ['1' '0' '2' '3+']
Education : ['Graduate' 'Not Graduate' 'G' 'NG' 'g']
Self_Employed : ['No' 'Yes']
Property_Area : ['Rural' 'Urban' 'Semiurban']
Loan_Status : ['N' 'Y']

In [ ]:
df1.dtypes

Loan_ID          object
Gender           object
Married          object
Dependents       object
Education        object
Self_Employed    object
Property_Area    object
Loan_Status      object
dtype: object

In [ ]:
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,Rural,N
2,LP001005,male,Yes,0,Graduate,Yes,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,Urban,Y
4,LP001008,M,No,0,G,No,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,Urban,Y
...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,Semiurban,N

In [ ]:
# Check for unique values in each column
unique_counts = df1.nunique()

# Find columns with all unique values
columns_to_drop = unique_counts[unique_counts == df1.shape[0]].index

# Drop columns with all unique values
df1 = df1.drop(columns=columns_to_drop)
df1

,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
1,Male,Yes,1,Graduate,No,Rural,N
2,male,Yes,0,Graduate,Yes,Urban,Y
3,Male,Yes,0,Not Graduate,No,Urban,Y
4,M,No,0,G,No,Urban,Y
5,Male,Yes,2,Graduate,Yes,Urban,Y
...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,Rural,Y
610,Male,Yes,3+,Graduate,No,Rural,Y
611,Male,Yes,1,Graduate,No,Urban,Y
612,Male,Yes,2,Graduate,No,Urban,Y
613,Female,No,0,Graduate,Yes,Semiurban,N

In [ ]:
df1.dtypes

Gender           object
Married          object
Dependents       object
Education        object
Self_Employed    object
Property_Area    object
Loan_Status      object
dtype: object

In [ ]:
import pandas as pd

# Specify the names of the columns you want to standardize
columns_to_standardize = df1.columns
# Add the names of the columns you want to standardize to this list

# Create a DataFrame to store the standardized data
standardized_df = df.copy()  # Start with a copy of the original DataFrame

# Iterate through the specified columns
for column_name in columns_to_standardize:
    if column_name in df.columns:
        # Process only the specified columns
        standardized_df[column_name] = standardized_df[column_name].str.capitalize()

for column_name in columns_to_standardize:
    if column_name in standardized_df.columns:
        # Define a function to convert single letters to the mode value
          def convert_to_mode(group):
              mode_value = group.mode().iloc[0]  # Calculate the mode of the group
              return mode_value

          # Apply the function to each group of values with the same starting letter
          standardized_df[column_name] = standardized_df.groupby(standardized_df[column_name].str[0])[column_name].transform(convert_to_mode)


# Now, the 'standardized_df' DataFrame contains the capitalized values for the specified columns.
standardized_df.head(7)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N

In [ ]:
standardized_df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
columns_to_standardize

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'Property_Area', 'Loan_Status'],
      dtype='object')

# For checking

In [ ]:
standardized_df['Gender'].value_counts()

Male      392
Female     88
Name: Gender, dtype: int64

In [ ]:
standardized_df['Married'].value_counts()

Yes    311
No     169
Name: Married, dtype: int64

In [ ]:
standardized_df['Education'].value_counts()

Graduate        383
Not graduate     97
Name: Education, dtype: int64

In [ ]:
standardized_df['Self_Employed'].value_counts()

No     414
Yes     66
Name: Self_Employed, dtype: int64